VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Threading"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Private mvarThread As Thread
Private Sub Class_Initialize()
    Set mvarThread = New Thread
End Sub
Private Sub Class_Terminate()
    Set mvarThread = Nothing
End Sub
Public Property Get Thread() As Thread
    Set Thread = mvarThread
End Property

